from datetime import date
name = input("Please type your name: ")
birth_year = input("Please enter your birth year: ")
birth_month = input("Please enter your birth month(e.g: if Jan type 01) : ")
birth_day = input("Please enter your birth day: ")
today = date.today()

Swork_year = input("Please enter your starting working year: ")
Swork_month = input("Please enter your starting working month(e.g: if Jan type 01) : ")
Swork_day = input("Please enter your starting working day: ")
Till_today_workExp = date.today()

age_year = today.year - int(birth_year) - ((today.month, today.day) < (int(birth_month), int(birth_day)))
age_month = abs(today.month - int(birth_month) - (today.month < (int(birth_month))))
age_day = abs(today.day - int(birth_day))

workingExp_year = Till_today_workExp.year - int(Swork_year) - ((Till_today_workExp.month, Till_today_workExp.day) < (int(Swork_month), int(Swork_day)))
workingExp_month = abs(Till_today_workExp.month - int(Swork_month) - (Till_today_workExp.month < (int(Swork_month))))
workingExp_day = abs(Till_today_workExp.day - int(Swork_day))

print("____________________________________________")
print("Hello " + name, ", welcome to python world")
print("--------------------------------------------")
print("You are", age_year, "years", age_month, "months", age_day, "days old")
print("|-----------------------------------------------------------|")
print("|+++++++++++++++++TOTAL WORKING EXPERIENCE++++++++++++++++++|")
print("|-----------------------------------------------------------|")
print("| Your total working experience is", workingExp_year, "years", workingExp_month, "months", workingExp_day, "days |")
print("|-----------------------------------------------------------|")
print("                                                                     ")
print("© Copyright protected", today.year)
print("O--------/")
print("/|     /|")
input("Please press any key to exit...")
